let strip = neopixel.create(DigitalPin.P1, 25, NeoPixelMode.RGB)
strip.showRainbow(1000, 100)
let rij3 = strip.range(10, 5)
let rij4 = strip.range(16, 3)
let rij5 = strip.range(22, 1)
let rij2 = strip.range(7, 1)
let rij1 = strip.range(2, 1)
strip.showColor(neopixel.colors(NeoPixelColors.Blue))
rij3.showColor(neopixel.colors(NeoPixelColors.Green))
rij4.showColor(neopixel.colors(NeoPixelColors.Green))
rij5.showColor(neopixel.colors(NeoPixelColors.Green))
rij2.showColor(neopixel.hsl(20, 100, 27))
rij1.showColor(neopixel.hsl(20, 100, 27))
